 
AllCops:
  TargetRubyVersion: 2.6.6
Metrics/LineLength:
  Max: 100
Metrics/BlockLength:
  Max: 75
Layout/MultilineBlockLayout:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false